# Generated by Django 5.1.3 on 2024-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='lat',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='lon',
            field=models.DecimalField(decimal_places=7, max_digits=11),
        ),
    ]
