# Generated by Django 5.1.3 on 2024-11-21 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_consulta_lat_alter_consulta_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='air_density',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='eficiencia_coefficients',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='eficiencia_generador',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='elevation',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='potencia_acumulada',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='potencia_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='potencia_promedio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='potencia_turbina',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='potencia_viento',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='weibull_curves',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='weibull_distribution',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='weibull_params_100m',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='weibull_params_10m',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='weibull_params_hm',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='wind_distribucion_acumulada',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='wind_rose_100m',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='wind_rose_10m',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='wind_speed_distribution',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='wind_speed_timeseries',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GraficasConsulta',
        ),
    ]
